name: Move

on:
  workflow_dispatch:

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          repository: vc-teahouse/Kernel-Builder
          run-id: '4'
          name: 'Anykernel3(phoenix_ztc1997-MIUI-phoenix-r-oss)'
